; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

DllCall("LoadLibrary", str, "scan.dll")

Gui -0x30000 ; remove maximize and minimize buttons
Gui Show, w170 h229, Memory Scanner
Gui Add, Edit, x5 y107 w120 h21 vregex
Gui Add, Text, x5 y82 w120 h23 +0x200, Enter a C++ Regex
Gui Add, Edit, x4 y45 w120 h21 vtitle
Gui Add, Text, x4 y22 w120 h21 +0x200, Enter the window title
Gui Add, Button, x4 y154 w122 h23 gscan, Scan
Gui Add, Text, x7 y180 w120 h23 +0x200 voutput, First match will show here
Return

GuiEscape:
GuiClose:
    ExitApp

scan() {
    GuiControlget,title,,title 
    GuiControlget,regex,,regex 
    GuiControl,, output, % DllCall("scan.dll\scan", AStr, title, AStr, regex, Astr)

}