; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Edit, x5 y107 w120 h21 vtitle
Gui Add, Text, x5 y82 w120 h23 +0x200, Enter a C++ Regex
Gui Add, Edit, x4 y45 w120 h21 vregex
Gui Add, Text, x4 y22 w120 h21 +0x200, Enter the window title
Gui Add, Button, x4 y154 w122 h23 gscan, Scan
Gui Add, Text, x7 y180 w120 h23 +0x200, First match will show here

Gui Show, w424 h429, Memory Scanner
Return

GuiEscape:
GuiClose:
    ExitApp

scan() {
    GuiControlget,title,,title 
    GuiControlget,regex,,regex 
    MsgBox % regex
    MsgBox % title
    DllCall("LoadLibrary", str, "scan.dll")
    MsgBox % DllCall("scan.dll\scan", AStr, "* Untitled - Notepad3 (Elevated)", AStr, "(@@@[a-z]{5,100}@@@)", Astr)
}